module.exports = [
  {
    key: 'home',
    name: 'Home',
    icon: 'ios-home-outline',
    // single: true,
    link: '/#',
    child: [],
  },
  {
    key: 'designs',
    name: 'Designs',
    icon: 'ios-color-palette-outline',
    single: true,
    link: '/#',
  },
  {
    key: 'coding',
    name: 'Coding',
    icon: 'ios-code',
    single: true,
    link: '/#',
  },
  {
    key: 'inspiration',
    name: 'Inspiration',
    icon: 'ios-bulb-outline',
    single: true,
    link: '/#',
  },
  {
    key: 'photo',
    name: 'Photogrphy',
    icon: 'ios-images-outline',
    single: true,
    link: '/#',
  },
  {
    key: 'lifestyle',
    name: 'Lifestyle',
    icon: 'ios-water-outline',
    single: true,
    link: '/#',
  },
];
